### ISSUE TITLE
Remove field "Date of Test Result" from all App Screens

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#102]
The field **Date of test result** is not used anymore since schema 1.3.0 and should be removed from all app screens because it is always empty.

Same issue in wallet app https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/issues/61

![image](https://user-images.githubusercontent.com/81565834/122251376-bcbab380-ceca-11eb-913e-f934b2c903d3.png)

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/103

**Comment by oleksandrsarapulovgl** [comment]
![Screenshot_1623921249](https://user-images.githubusercontent.com/82441124/122368646-2fc53800-cf66-11eb-9b62-522f46d0067d.png)
