### ISSUE TITLE
Field "valid until" for recovery is not checked in Android - should be equal to iOS App check

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#104]
![image](https://user-images.githubusercontent.com/81565834/122409011-18487800-cf83-11eb-879b-6bb941721da3.png)

If the date in the **valid until** field is expired, certificate should not longer be vaild.

The behaviour should be the same like in iOS App so that both apps show the same certificate status and message.

**Comment by SchulzeStTSI** [comment]
https://github.com/SchulzeStTSI/dgca-verifier-app-android/commit/5c53221c69579a9d184751ca040bbc3080a92b18
https://github.com/SchulzeStTSI/dgca-app-core-android/commit/48534b5939b983e6c4a2b16f013944a99105b074
https://github.com/SchulzeStTSI/dgca-app-core-android/commit/bfa1849574072ca1dc1def9f6c6cb459dde87938
https://github.com/SchulzeStTSI/dgca-app-core-android/commit/ebbb5a9d7934e201f6ac7e7cc24409936bf98533
https://github.com/SchulzeStTSI/dgca-app-core-android/commit/af1010166e4e7d917bbd67cf8b76b1febee024f9
