### ISSUE TITLE
[Android] Scanned Certificate Cannot be Scrolled Up or Down

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#112]
## Describe the bug

A scanned certificate cannot be scrolled up or down.  This leads to the problem that not all payload data can be seen., because it does not fit the screen.

## Expected behaviour

The scanned certificate can be scrolled up and down, so that all payload data can be seen,

## Technical details
Galaxy XCover 4, Modellnummer: SM-G390F,
Android-Version: 9

## Additional context

Bug is observed in both versions for the environments TST and ACC.

**Comment by kerstin-oppermann-tsi** [comment]
Retested in release 1.0.7.
