### ISSUE TITLE
Validation app crashes when COBR datetime field is taged with 0 tag

### ISSUE THREAD

**Issue by Tomas-Alb** [eu-digital-green-certificates/dgca-verifier-app-android#123]
## Describe the bug

Regarding specifications  - DateTime fields in COBR should be tagged with 0 tag. New version of validation app crashes when datetime field is tagged with 0 tag. 

Issue could be found in 

 https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/blob/main/app/src/main/java/dgca/verifier/app/android/verification/VerificationViewModel.kt#L183
 
```
validationResults = engine.validate(
    this.greenCertificate.schemaVersion,
    JSON_SCHEMA_V1,
    rules,
    externalParameter,
    this.hcertJson
)
```

this.hcertJson contains not valid josn with COBOR 0 tag:

{"t": [{"sc": 0("2021-06-10T10:11:42.000Z"), "nm": "SARS-COV-2 viruso sukeltos COVID-19 ligos diagnostika (Diagnostic of COVID-19 disease caused by SARS-CoV-2 virus)", "tt": "LP6464-4", "co": "LT", "tc": "VIEŠOJI ĮSTAIGA CENTRO POLIKLINIKA", "ci": "URN:UVCI:01:LT:44CM2COVWRYXTSQ6HZKBP#C", "is": "LR sveikatos apsaugos ministerija", "tg": "840539006", "tr": "260415000"}], "nam": {"fnt": "PAVARDENYTE<PAVARDENE", "fn": "Pavardenytė-Pavardenė", "gnt": "BIRUTE<MARIJA", "gn": "Birutė-Marija"}, "dob": "2000-10-03", "ver": "1.0.0"}

So validation engine crashes because of unexpected character.

## Expected behaviour

The validation app should remove the 0 tag from COBOR and set this.hcertJson to valid Json.

## Steps to reproduce the issue

1. Create Test certificate and tag sc value with 0 tag
2. Scan QR with validation app

Or just scan our QR

 [https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/LT/png/2.png](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/LT/png/2.png)

**Comment by SchulzeStTSI** [comment]
@Tomas-Alb Can you provide an QR Code?

**Comment by ragaisis** [comment]
@SchulzeStTSI it's in the bottom of the message 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/LT/png/2.png

**Comment by SchulzeStTSI** [comment]
@ragaisis Thank you:)

**Comment by SchulzeStTSI** [comment]
@oleksandrsarapulovgl Please use this for test: https://github.com/eu-digital-green-certificates/dgc-testdata/blob/ab8b934c1f698350c82151c1316d2a74e903535b/LT/png/2.png Problem occurs in the cborObject.toString() method  (which attaches "0() to the string)  https://github.com/eu-digital-green-certificates/dgca-app-core-android/blob/main/decoder/src/main/java/dgca/verifier/app/decoder/cbor/DefaultCborService.kt#L67

**Comment by oleksandrsarapulovgl** [comment]
@SchulzeStTSI I rechecked QR, and with changes from the PR: https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/46, it works properly.

**Comment by SchulzeStTSI** [comment]
@Tomas-Alb can we close the issue?
