### ISSUE TITLE
Explain the difference between the "acc" and the "tst" version

### ISSUE THREAD

**Issue by jondo** [eu-digital-green-certificates/dgca-verifier-app-android#128]
I want to use this app, but I don't know whether to user `app-acc-release-signed-1.1.3-RC-1.apk` or `app-tst-release-signed-1.1.3-RC-1.apk`. I assume that the `app-acc` is the correct one, and `app-tst` is just some version for development tests? Please describe this.

**Comment by daniel-eder** [comment]
The apps provided in this GitHub organization are only templates that member states can adapt for their purposes. They can be used as-is, but would need to be configured to work with the respective member state backends.

Both tst and acc are builds that are part of the testing strategy and do not interact with the production environments, as production environments are under the responsibility of the member states, not the EU.
