### ISSUE TITLE
Please release on F-Droid

### ISSUE THREAD

**Issue by jondo** [eu-digital-green-certificates/dgca-verifier-app-android#129]
I am using an Android version without Google services, so please release this app on F-Droid.

**Comment by daniel-eder** [comment]
The apps in this organization are template apps that are not directly released, rather the member states use them as basis for their own apps. As the member states are responsible for the trust list to verify authenticity of certificates, the app cannot be used in production without proper configuration by a member state. 

To obtain a working copy, you need to install the app your member state provides and/or request them to make their copy available on F-Droid
