### ISSUE TITLE
"Validate with" country should be remembered

### ISSUE THREAD

**Issue by jondo** [eu-digital-green-certificates/dgca-verifier-app-android#130]
I have installed `app-acc-release-signed-1.1.3-RC-1.apk`.
When I open the app, the "Validate with:" field is set to "Belgien", the topmost dropdown list value. When I change this to "Österreich", then open and close the settings, the field has switched back to "Belgien". The same happens when I close and reopen the app.

The new field value should of course persist instead.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/137

**Comment by kerstin-oppermann-tsi** [comment]
@oleksandrsarapulovgl @Hendrik-Schmidt-Schierhorn-TSI 
In release 1.1.5.-acc tthis issue is still there. When I put the app in the background and open it again the country list is set to Belgien.

**Comment by kerstin-oppermann-tsi** [comment]
fixed in release 1.1.6
