### ISSUE TITLE
[Android] No rule is displayed when the rule is valid

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#133]
## Describe the bug

The rule VR-BE-0001 for Belgium is only displayed when it is not valid. When it is valid, no rule is displayed.

The rule states that every day before 12 o'clock noontime only the Vaccine Biontech is valid. Then -- after12 o'clock noontime only Moderna is valid.  That is, the rule alternates every 12 hours between Biontech and Miderna.  The rule is enacted on 08. July so to test it we used time travel.

## Expected behaviour
We expect that the rule is also shown in the case when it is valid.

## Steps to reproduce the issue

1. Set mobile time to 08. July, any hour before 12 o'clock lunch
2. Scan Certificate Code with country Belgium
![Biontech](https://user-images.githubusercontent.com/76050122/124722498-67daed80-df0a-11eb-9384-6c38f9a8f029.png)

## Technical details
Android Verifier App 1.1.4-tst

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY , this is a correct behavior. Could you please check the rules you expect to be checked? The `validFrom` date for them is "2021-07-08T22:00Z". You device clock is before the time, so these rules shouldn't be validate.

**Comment by RalicaY** [comment]
The ticket is obsolete given the attached example and the current date.  In case a similar behaviour is observed, a new ticket will be created with the specific set up to recreate it.
