### ISSUE TITLE
"Verification failed" for all certificates

### ISSUE THREAD

**Issue by daviddem1971** [eu-digital-green-certificates/dgca-verifier-app-android#134]
Tried acc and tst releases and I always get "verification failed" no matter what certificate I try to validate or country I choose to validate with. I know the certificatess are valid since I can validate them with the covidcheck.lu app.

What could be the problem?

**Comment by daniel-eder** [comment]
The acc and tst releases are not productive releases, they are connected to the acceptance and test environments respectively.
The apps on here are only templates developed for further use by the member states. As only member states (not the EU) have sovereignty over the list of public keys (trustlist) that are used to validate certificates, only the member states can make (or enable third parties to make) production-ready apps, see also https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
