### ISSUE TITLE
EU production-ready app

### ISSUE THREAD

**Issue by daviddem1971** [eu-digital-green-certificates/dgca-verifier-app-android#136]
Does the EU plan to release an official production-ready app that can be used by anyone, similar to what Luxembourg did with the covidcheck.lu app?

If not, how are officials and airlines at border points outside the EU supposed to verify the authenticity of our EU vaccine certificates? At the moment, we have vaccination certificates with QR codes that can only be read by officials within the EU and/or people savvy enough (NOT your average immigration official in a developing country) to know that they can use the covidcheck.lu app to do so.

There should be a very prominent and widely advertised app from the EU for this purpose imo. Most countries I travel to these days are ALREADY requesting vaccination certificates to facilitate entry, and are only asking to accept foreign certificates, if only they can authenticate them easily...

**Comment by daniel-eder** [comment]
While this is a valid concern, such an app is not planned.

There are various political decisions behind this, but simply put, the member states and not the EU have sovereignty over the certificate validation (both who can access their infrastructure to validate certificates, and when a certificate is considered valid/sufficient for a specific purpose such as entering the country or e.g. an event venue).

Non-EU countries need to get in touch with the European Commission to clarify how they can validate certificates.

**Comment by daniel-eder** [comment]
Closing this as this actually is the same topic as https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
