### ISSUE TITLE
Android - If test result is positiv (DETECTED) the business rule check should display a red invalid status of the cert (instead of orange)

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#138]
If a test result is positiv the verifier should get an red invalid status because this should be recognized at first glance.

Actual status:
![image](https://user-images.githubusercontent.com/81565834/124887278-4e52a800-dfd5-11eb-9112-9e139b3355b7.png)

Expected status:
Invalid status

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/141

**Comment by kerstin-oppermann-tsi** [comment]
fixed in release 1.1.6
