### ISSUE TITLE
[Android] Signing certifiate expiration date time does not supercede the expiration date time of the green certificate

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#142]
## Describe the bug

In order  to check, that when the signing certificate expiration datetime supersedes the expiration datetime in the Green certificate, the app returns INVALID we have created the following QR-Code with chronologically valid certificate but with an expired DSC Certificate.  

Attached JSON file and QR Code. 

Nevertheless, scanning this QR Code with the Verifier app returns VALID.

## Expected behaviour

Expected is a RED screen saying the Certificate is INVALID.

## Technical details

Verifier 1.1.5-tst
![signing_expiration_supercedes_certificate_expiration](https://user-images.githubusercontent.com/76050122/125065034-9f37ce80-e0b1-11eb-9f25-a83334ed3009.jpg)
![signing_expiration_supercedes_certificate_expiration_json](https://user-images.githubusercontent.com/76050122/125065206-d5754e00-e0b1-11eb-9c77-c25df2adca33.jpg)

Galaxy XCover 4, Android 9

**Comment by kerstin-oppermann-tsi** [comment]
@Hendrik-Schmidt-Schierhorn-TSI @oleksandrsarapulovgl Can you check this issue please. I do not clearly understand this...

**Comment by RalicaY** [comment]
The idea is that the Certificate is indeed chronologically valid but the signer's certificate is already expired so that the certificate's expiration time eventually supercedes (is valid longer than ) the signer's.

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY @Hendrik-Schmidt-Schierhorn-TSI I tested this QR - and BE is not returning public key for the QR.

@RalicaY do you have other QR to test this?

**Comment by RalicaY** [comment]
@TKlauenberg, could you please provide us with another QR Code?

**Comment by TKlauenberg** [comment]
@oleksandrsarapulovgl the QR-Code is signed with the Certificate with the kid '9T3aGXtSul0='. This Certificate is only in the TST environment. If I would create another QR-Code it would be signed with the same public key.

**Comment by ltranvan** [comment]
@oleksandrsarapulovgl @Hendrik-Schmidt-Schierhorn-TSI : the reason from my view might be "Signing Certificate is expired" Hendirk, it is ok?

**Comment by oleksandrsarapulovgl** [comment]
So far I implemented to show "Verification failed", as we show for the case there is no key to validate over.

@Hendrik-Schmidt-Schierhorn-TSI could you please clarify if we need to show: "Signing Certificate is expired"?

**Comment by oleksandrsarapulovgl** [comment]
Another PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/160

**Comment by RalicaY** [comment]
Successfully retested with Invalidity Notification "Verification Failed"
