### ISSUE TITLE
[Android]  Scanning a certificate, created with a not supported Schema-Version does not result in INVALID as expected 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#143]
![version2 0 json](https://user-images.githubusercontent.com/76050122/125250445-8ec46580-e2f6-11eb-9f0e-868fc5db06cd.png)

## Describe the bug

Given the certificate with a higher Version 2.0.0 than the current, scanning it should result in INVALID.

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by kerstin-oppermann-tsi** [comment]
@Hendrik-Schmidt-Schierhorn-TSI commented in the according iOS issue:

_The reason for this behaviour is, that the Schema-Version is colliding with the Business-Rules. That leads to rules with the state "open".
The Code itself can be read and is valid, so we should not show the Invalid-Screen.

I think, we can close this Issue._

According to this I will close the issue.  @RalicaY
