### ISSUE TITLE
Android - App crash on device rotation

### ISSUE THREAD

**Issue by fneur** [eu-digital-green-certificates/dgca-verifier-app-android#145]
## Describe the bug

In scan mode (i.e. CodeReaderFragment) when you rotate the device from vertical to horizontal position, the app crashes.

## Expected behaviour

Proper update of the device display (without crashing).

## Technical details

The problem is due to the following code in CodeReaderFragment:
`fun onItemSelected(parentView: AdapterView<*>?, selectedItemView: View, position: Int, id: Long)`

## Possible Fix

Replace `View` by `View?`:
`fun onItemSelected(parentView: AdapterView<*>?, selectedItemView: View?, position: Int, id: Long)`

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/148

**Comment by fneur** [comment]
@oleksandrsarapulovgl thanks for the quick fix. This issue can be closed.

**Comment by oleksandrsarapulovgl** [comment]
Thank you! Closing
