### ISSUE TITLE
Duplicate entries and non EU countries in the list

### ISSUE THREAD

**Issue by skounis** [eu-digital-green-certificates/dgca-verifier-app-android#147]
## Describe the bug
The list of the countries displays values that should not be there
1. Duplicate entry for Greece
2. Myanmar (non EU country)
3. DX: Where this refers to?
4. European Union: Do we need this entry, are there cases where this option is used?

![WIN_20210714_12_58_41_Pro_LI](https://user-images.githubusercontent.com/690575/125611643-cf0f34f6-29cb-4ee2-97b7-c44deeec4a98.jpg)

## Steps to reproduce the issue

1. Download the android app (acc build)
2. Click and reveal the countries list

## Technical details

- Android Pixel 2 - built 1.1.5-acc

**Comment by oleksandrsarapulovgl** [comment]
PRs:
https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/39

https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/84
https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/151
