### ISSUE TITLE
[Android] -- Leaving the settings dialog leads to app crash

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#149]
## Describe the bug

When coming out of the settings dialog via the tree dots in the upper right corner, upon pressing the arrow in the upper left corner, the app crashes.

## Steps to reproduce the issue

1. Click the three dots in the upper right corner to enter the settings menu;
2. Then press the arrow in the upper left corner --> app crashes.

## Technical details
Android Verifier 1.1.6-tst
Galaxy XCover 4, Android 9

https://user-images.githubusercontent.com/76050122/125783242-7651eafc-59a3-4ef0-af6d-941447d9efaa.mp4

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY , I checked the issue, and wasn't able to reproduce it. I suspect I fixed that in latest build. Could you please check on the latest build (https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/releases/tag/1.1.7-RC-1), and if it's reproducing - provide logs of the crash?

**Comment by RalicaY** [comment]
Retest successful, Android Verifier 1.1.7-tst
