### ISSUE TITLE
Android - Verifier App didn't check the HC1 prefix in QR Code

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#152]
## Describe the bug
According to the hight prio issue for iOS that the HC1 prefix is removed in the resultant QR Code in Wallet app
https://github.com/eu-digital-green-certificates/dgca-app-core-ios/issues/83

we found out that the verifier apps didnt check the HC1 prefix.

The  QR Code with no HC1 prefix is scanned by the verifier app as valid but should be invalid.

## Expected behaviour

The  QR Code with no HC1 prefix iis invalid.

QR Code from iOS wallet ACC

![image](https://user-images.githubusercontent.com/81565834/125974126-6e8e2da7-0178-46ec-8764-a040e1711044.png)

QR Code : 6BFOXN%TSMAHN-HR S7OQLQ7P:I/F8/R8PJE2FC$K9J2T5DO:.IEHEUD7EP4R1BF/8X*G-O9UVPQRHIY1+ HNQ1 WUQRELS400TXRVJR2B+2D-4Q/S6AL*IHRV%Q0U*0NK7GMV /KI-KO5L$W20YC9Y4KCTWZK/SNKV0ADF9Y4.$S6ZC0JB3I3KD38D0MJC7ZSA KZ*U0I1-I0*OC6H0/VMNPM Q5TM8*N9-I06H00YQK*R3T3+7A.N88J4R$F/MAITH-+R2YBV44PZB6H0CJ0%H0%P8C K1U70%KLR2C KPLIUM42CGCHGL%5%DBF.7F.OZJJ.V47NV/HLSY4L8S1JPTQNZEFHAPDZISP4*2DS9DU*0CEBQ/GXQF8$G5LBYDNOOV+QJW774338Q0V77$OFI6H:Q8:Q8797W0H2DNL*87-VOZE32ORAUQET-QIY+I23D47QD.V7*M2OTXNIYDKO3E9$2 IAS.LEO40R2-7RQESPNFNHEHQCZS:M2D+L9 M$1LT185.2*YSC9QN20QB6K1

**Comment by oleksandrsarapulovgl** [comment]
PR for the verifier app: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/153
