### ISSUE TITLE
Extract Kotlin Verifier Code in a seperate library

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-verifier-app-android#16]
The android app contains verifier code which can be used in the backend for testing as well. To support this, the code must be outsourced into a seperate library.

**Comment by oleksandrsarapulovgl** [comment]
Closed at PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/20

**Comment by oleksandrsarapulovgl** [comment]
Fixed at:

https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/22
https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/4
