### ISSUE TITLE
Remove Country Selector

### ISSUE THREAD

**Issue by EdossProject** [eu-digital-green-certificates/dgca-verifier-app-android#167]
Hi,
Can i remove Country Selection button from my app?
![image](https://user-images.githubusercontent.com/88037505/127293959-35cc0571-41cd-492b-a4b4-208a31b08f5b.png)

**Comment by EdossProject** [comment]
i wont to set ITALY is Only One Active

**Comment by mitjap** [comment]
What does this selection do?

**Comment by oleksandrsarapulovgl** [comment]
@EdossProject @mitjap this selection identifies which country rules to verify certificate over.

So, we have 2 features here: verification of green certificate validity, and verification of certificate over the rules of specific country.

**Comment by oleksandrsarapulovgl** [comment]
So, I think you can remove this selector from your app @EdossProject , you will just need to hardcode Italy country iso code to be passed to cert logic validation module for further check up

**Comment by EdossProject** [comment]
@oleksandrsarapulovgl can you help me to do this?

**Comment by oleksandrsarapulovgl** [comment]
How may I help you exactly?

**Comment by daniel-eder** [comment]
@EdossProject the support in this organization is focused on assisting EU member states with implementing their apps, mainly with topics specific to DCCs. We do not have the capacity to provide support for general android development. Please visit other forums, such as stackoverflow.com for more general coding issues.
