### ISSUE TITLE
App not recognizing QR code

### ISSUE THREAD

**Issue by wearekolossum** [eu-digital-green-certificates/dgca-verifier-app-android#174]
Hey,

i tried the app, generated a QR code and all but when i try to scan it with the app it doesn't do anything. It focus on the QR code, then "freeze" for around 1 second and then start over, so focus again, freeze for 1 second and then again and again and again. Any ideas?

Thanks and take care
Florian

**Comment by daniel-eder** [comment]
@wearekolossum could you share the problematic QR code here? 
Thank you!

**Comment by wearekolossum** [comment]
Hey @daniel-eder , sure thing. Find attached. It should be a quicktest result URL for the CWA in there. So maybe that's why it is not working? Can i only verify other results with the app? 

Thanks in advance and take care
Florian

![Bildschirmfoto 2021-08-03 um 09 07 56](https://user-images.githubusercontent.com/9267294/127972839-82376ec3-2d5a-4368-8aef-2d482105b7b0.png)

**Comment by oleksandrsarapulovgl** [comment]
@wearekolossum content of your QR code doesn't follow necessary structure.

Content is the next: https://s.coronawarn.app?v=1#eyJ0aW1lc3RhbXAiOjE2Mjc5Mjc1MjcsInNhbHQiOiIzQkNGMEM4MDFGRkY2NkUwMjA5MjNEMjczNjNBNDVERSIsImhhc2giOiJmZjMzZjdkOWRlMDcwZWMzMWU5NGExNzgwMzRhNzg2YzU1N2Q0ZmJjOWYxNWI3MGYxNzNjN2Y5Mjk0ZTZiMWI4In0

Please get sure your QR code content structure follows the checks done here: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/blob/1f4e521ba13a8f1dc5d73cc58d83ec3ff1299282/app/src/main/java/dgca/verifier/app/android/verification/VerificationViewModel.kt#L147

**Comment by wearekolossum** [comment]
Hey @oleksandrsarapulovgl ,

thanks for your response. I generated the code according to https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme-ohne-DCC which says that the content of the QR code should be such a link. That's why i asked: are those quicktest link QR codes not verifiable with the app?

And wouldn't it be a good idea to, when the content of the QR code is not correct, give the user any kind of feedback?

Thanks and take care
Florian

**Comment by wearekolossum** [comment]
Hey @oleksandrsarapulovgl , thanks for the info. So i guess quicktest results are just not verifiable with the app. 

Thanks anyways and take care
Florian
