### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by superasty** [eu-digital-green-certificates/dgca-verifier-app-android#183]
## Describe the bug

I have make projet dgca-verifier-app-android-main last version but I read this message:

Could not determine the dependencies of task ':app:lintAccDebug'.
> Could not resolve all artifacts for configuration ':app:tstDebugCompileClasspath'.
   > Could not resolve project :engine.
     Required by:
         project :app
      > No matching configuration of project :engine was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'version' with value 'tst', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

**Comment by MykhailoNester** [comment]
From this error I see that you don't have  project `:engine`

Please check Build section from readme:
https://github.com/eu-digital-green-certificates/dgca-verifier-app-android#build

In your case `dgc-certlogic-android` - is missing
