### ISSUE TITLE
Android - BUG - vaccination, test or rec dates in the future should be hard rejected like in the iOS app. (Different Error Message on DCCs issued in the future)

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgca-verifier-app-android#185]
## Different Error Message between Android and IOS

For testdata I had created a dcc with the IssuedAt Header (in the Cose Message) in the future. When I am scanning that certificate the IOS Verifier App shows the Error "Certificate Isssuance Date is in the future". The Android App shows "Cryptographic signature invalid".

## Expected behaviour

Both apps show the Error message "Certificate Isssuance Date is in the future".

## Steps to reproduce the issue

![SC_VAC_1](https://user-images.githubusercontent.com/15056506/130016936-81d04601-67c3-49d1-8916-f50ecf12e5f5.png)

This QR Code has an IssuedAt Value of 2021-08-30. The certificate should be scannable by the App for the Acceptance Environment.

**Comment by kerstin-oppermann-tsi** [comment]
Android without debug mode:
![image](https://user-images.githubusercontent.com/81565834/133409017-ee071126-5bf0-4f0d-97a4-fc76e74ddcc4.png)

iOS without debug mode:
![image](https://user-images.githubusercontent.com/81565834/133409145-78a7ddaa-aedf-4b92-bd88-1380add9037d.png)


Android with debug mode:
![image](https://user-images.githubusercontent.com/81565834/133409669-e4ce4941-5df4-421b-8325-133f9d38b089.png)

iOS with debug mode:
![image](https://user-images.githubusercontent.com/81565834/133409721-57879c9e-c021-498e-a004-096c70008cb1.png)

**Comment by kerstin-oppermann-tsi** [comment]
@chrloch you can have a look on my provided screenshots of the actual apps. Seems that is not the same message, but the main outcoming is correct for both apps? Or what do you think?

**Comment by kerstin-oppermann-tsi** [comment]
![image](https://user-images.githubusercontent.com/81565834/133431379-198e03fa-f72f-4424-9960-8aa010642dbb.png)
certificate created on ACC Vaccination 2/2 on 30th of september 2021 (date is in the future)

Android shows that the certificate is valid:
![image](https://user-images.githubusercontent.com/81565834/133431560-1721cc6f-6e38-4b27-8bc6-67904458529b.png)

iOS shows correct that the date is in the future:
![image](https://user-images.githubusercontent.com/81565834/133431671-281b5d09-21c6-4591-a3a7-3e37fd3b0d60.png)

**Comment by kerstin-oppermann-tsi** [comment]
![image](https://user-images.githubusercontent.com/81565834/133759803-915c8fa0-269d-47a8-aba3-a17d039a6347.png)

Android:
![image](https://user-images.githubusercontent.com/81565834/133760176-94ca9e45-42ee-4b9c-b347-64e0ce3a700b.png)

iOS:
![image](https://user-images.githubusercontent.com/81565834/133760247-25058a34-8e80-49e5-8540-7407e64bc142.png)

At the moment we have this different behaviour on Android and iOS. Both is correct, but different handling.

@chrloch @TKlauenberg Wie wollen wir damit umgehen?

**Comment by chrloch** [comment]
Bei Android erfolgt die Ablehnung offenbar nur aufgrund der Business Rules. Wenn die nicht korrekt synchronisiert wurden oder ein Land ausgewählt wurde, das keine Regel auf das Impfdatum hat, dann wird es grün.

Meiner Meinung nach sollte Android ein Impfdatum in der Zukunft hart abweisen.

**Comment by kerstin-oppermann-tsi** [comment]
@chrloch ja stimmt da hast du Recht !!

**Comment by kerstin-oppermann-tsi** [comment]
@MykhailoNester @oleksandrsarapulovgl @Hendrik-Schmidt-Schierhorn-TSI according the comment of Christian, can you please have a look on this ticket.

On Android, the rejection is apparently only based on the business rules. If they were not synchronized correctly or a country was selected that has no rule on the vaccination date, it will turn to valid and green.

In my opinion, Android should hard reject a vaccination date in the future like iOS does.
