### ISSUE TITLE
Scottish NHS Vaccine Status

### ISSUE THREAD

**Issue by RyanDrewTravers** [eu-digital-green-certificates/dgca-verifier-app-android#189]
I'm double vaccinated in Scotland but there is currently no QR code on the Scottish NHS vaccine status certificate and also no Scottish Covid Pass. Is there a way to be verified for when travelling in Italy for double vaccinated Scots? There seems to be a general lack of appreciation that there is no such thing as a "UK" QR code but instead there is an England & Wales one, a NI one but no Scottish one.

**Comment by daniel-eder** [comment]
@RyanDrewTravers as this GitHub organization is mainly targeted at technical solutions within the EU and third countries, it is unlikely that someone here will be able to answer your question (as the background there is mainly political). You may be best served directing it at your national health authority, or Italy's. 

That said, if you visit the slack workspace ( invite can be found in the overview table on https://github.com/eu-digital-green-certificates/dgc-overview ) there is a good chance someone working on the national solution for Italy or the solutions within UK is in there as well and can help with further steps
