### ISSUE TITLE
Scan diretto

### ISSUE THREAD

**Issue by cadaniele** [eu-digital-green-certificates/dgca-verifier-app-android#190]
## Feature description
Buongiorno, vorrei suggerire la possibilità di valutare l’implementazione di recepire il qrcode senza aprire la fotocamera ma direttamente da scanner del dispositivo su cui è installata l'app.
Molti dispositivi che già leggono ad esempio i codici dei biglietti di ingresso potrebbero sfruttare lo scanner del dispositivo senza dover passare dalla fotocamera.
Noi ad esempio usiamo questi terminali https://www.zebra.com/it/it/products/spec-sheets/mobile-computers/handheld/tc21-tc26.html già dotati di scanner ma dobbiamo comunque inquadrare il qrcode della certificazione verde con la fotocamera perché ad una scansione tramite scanner l'app VerificaC19 non risponde.
Grazie e buona giornata

**Comment by daniel-eder** [comment]
This feature is somewhat out of scope for the solution in this repository, as it only aims to be a reference / template implementation for EU member states to use in their own apps. If you would like to see this functionality in VerificaC19, please get in touch with the developers of the app directly to suggest such a feature
