### ISSUE TITLE
Android - BUG - Rules are not checked on ACC

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#212]
During my tests for the issue 

https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/185

I recognized that the Android Verifier App doesn’t check against vaccination rules (first it was after reinstallation on TST or ACC but now it is on ACC anytime).
On ACC I never got a vaccination rule check (iOS did) on TST it takes about sometimes 20 minutes till the first rule check works.
For recovery certificates it works (sometimes) on both environments. 

Please can you check this behaviour (maybe on fresh installtion of the apps)

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment]
This seems to be an Issue related to the problems we are facing currently with the Backend.

**Comment by kerstin-oppermann-tsi** [comment]
Works with the new backend environment on ACC with app version provided in app center
