### ISSUE TITLE
Verifier library?

### ISSUE THREAD

**Issue by lucrus73** [eu-digital-green-certificates/dgca-verifier-app-android#213]
Is there a library that I can use to implement the DGC verification in a web app (such as NodeJS or Angular)? Assuming Typescript language (but any other will do) I'm looking for something like:

```
import { DGCVerifier } from 'dgcverifier';

DGCVerifier.verify(pngFileOfTheQrCode).then(...).catch(...);

```
which is not tied to any specific client OS.

**Comment by daniel-eder** [comment]
There is no web app or library for a web app that are part of this project, the only sample implementations are for Android and iOS.
However you may find code samples and snippets in additional languages and environments here: https://github.com/ehn-dcc-development
