### ISSUE TITLE
endpoint return 404 error

### ISSUE THREAD

**Issue by ricci69** [eu-digital-green-certificates/dgca-verifier-app-android#218]
## Describe the bug

The endpoint https://dgca-businessrule-service-eu-acc.cfapps.eu10.hana.ondemand.com/rules is returning 404 error.
The endpoint are declared in file  dgca-verifier-app-android/app/src/acc/assets/verifier-context.jsonc 
The APP is not working because it hasn't the certificates.

## Expected behaviour

Return the json response with all the country rules

## Steps to reproduce the issue

Open the browser
Navigate to https://dgca-businessrule-service-eu-acc.cfapps.eu10.hana.ondemand.com/rules

## Technical details

Any

## Possible Fix

Fix the endpoint

**Comment by ortorob73** [comment]
same problem here

**Comment by saggy18** [comment]
Also our app stopped working this morning and, after checking, we found to be this same issue. Please put back the missing url so our app can work again, while we update to new code.

It is vital important!!! Our solution is used by schools and we need to finish deliver the app tomorrow. Thanks

**Comment by psavva** [comment]
@SchulzeStTSI Please review, email also sent with info from Italy

**Comment by SchulzeStTSI** [comment]
@psavva Thank you very much for forwarding! I've answered him already.

**Comment by SchulzeStTSI** [comment]
@saggy18 @ortorob73 @ricci69 The ACC Environment is just a test environment, and we switched it off 2 days ago i cause of a very high amount of traffic (the ACC Rules/Certs are not productive, so their value is limited) and to find out who is using it. All offical representives were informed multiple times. The context.json itself needs to be replace by the national endpoints.
To find a solution for you please tell me your country, the projectname/company and i can contact the eHealth GOV representives for you to highlight that there is a urgent demand to have the ACC endpoints for testing or later on productive endpoints.

We switch on now the Endpoints again, but we will switch if off next week by monday night again. Please prepare an update so quick as possible.

**Comment by ricci69** [comment]
> @saggy18 @ortorob73 @ricci69 The ACC Environment is just a test environment, and we switched it off 2 days ago i cause of a very high amount of traffic (the ACC Rules/Certs are not productive, so their value is limited) and to find out who is using it. All offical representives were informed multiple times. The context.json itself needs to be replace by the national endpoints.
> To find a solution for you please tell me your country, the projectname/company and i can contact the eHealth GOV representives for you to highlight that there is a urgent demand to have the ACC endpoints for testing or later on productive endpoints.
> 
> We switch on now the Endpoints again, but we will switch if off next week by monday night again. Please prepare an update so quick as possible.

I am just a programmer who is trying this program out of curiosity and to see if there are any bugs.
If the test endpoint is down, how can I test it? I was using the green pass from the repository https://github.com/eu-digital-green-certificates/dgc-testdata
Or is there a way to disable this control, since it is not necessary for testing purposes?

**Comment by EdossProject** [comment]
Hi, is it possible to have ENDPOINTS for Italy? Our solution is available in restaurants and other outlets.

**Comment by daniel-eder** [comment]
@EdossProject please view https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for more information on this.

Simply put, for Apps hosted in italy you need to get in touch with Italy's national health authority to organize official access to their national backend.

**Comment by simudvarac** [comment]
> @saggy18 @ortorob73 @ricci69 The ACC Environment is just a test environment, and we switched it off 2 days ago i cause of a very high amount of traffic (the ACC Rules/Certs are not productive, so their value is limited) and to find out who is using it. All offical representives were informed multiple times. The context.json itself needs to be replace by the national endpoints. To find a solution for you please tell me your country, the projectname/company and i can contact the eHealth GOV representives for you to highlight that there is a urgent demand to have the ACC endpoints for testing or later on productive endpoints.
> 
> We switch on now the Endpoints again, but we will switch if off next week by monday night again. Please prepare an update so quick as possible.

@SchulzeStTSI Could you please be so kind and point me to the right representatives for Germany? We are working on a 2G checking solution and need some official Endpoint to connect to. Thank you!
