### ISSUE TITLE
[Android] No Option for Setting Anonymisation

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#219]
## Describe the bug

According to the specification, s. chapter **8.3 Anonymous DCC Export**, the anonymisation of the personal data in the qr code should be selectable by the user of the app and must follow the rules of the DCC Anomaly Capture Process.

At the moment there is no way to select the anonymisation of the personal data by the user of the app.

## Expected behaviour
The anonymisation should be selectable by the user of the app.

## Technical Details
Verifier App 1.2.2-acc
Galaxy XCover 4, Android 9

**Comment by MykhailoNester** [comment]
Hi @RalicaY in settings user can select one of three level of anonymization

![device-2021-09-27-130541](https://user-images.githubusercontent.com/9447674/134888723-d815fae1-7a4a-46a4-9dad-2aec5136811e.png)

**Comment by RalicaY** [comment]
@MykhailoNester, the setting You are describing is the level of "Debug Mode".  The "Debug Mode" levels is just for setting the details view, not for anonymisation, please see chapter 8.2 "Details View".

**Comment by ltranvan** [comment]
After discussion with Steffen S. (Author of the SPEC-document) and Hendrik (development) following resolution:
- Anonymization option is coupled to the debug mode option. (means there is no extra option for anoynmization).
- Anonymization is only used for personal data in the shared files only for debug level 1 and level 2.
- The anonymisation option should be selectable only by the user of the Verifier App, not for the holder of the ceertificat
So in case that the software is implemented correctly as described above, it is then correct and the ticket can be closed.

**Comment by RalicaY** [comment]
Successfully retested,
Verifier App 1.2.4-acc (28)
Galaxy XCover 4, Android 9
