### ISSUE TITLE
[Android] Valid VAC Code is shown as " Cryptographic Signature Invalid" 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#221]
## Describe the bug
The following [VAC code ](https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/b7d31605aeda1adb805f6bfaed27e126920d3077/AM/1.3.0/VAC.png)is evaluated as INVALID by the Android Verifier with stated reason "Cryptographic Signature Invalid".

Yet, the Code is valid and iOS Verifier accepts it as valid.

## Expected behaviour

Payload is shown and a green VALID result is shown.

## Technical details
Android Verifier 1.2.0-RC-1
![VAC_ARMENIA](https://user-images.githubusercontent.com/76050122/134881749-3ff3e071-ede4-456b-beb7-934c5e461975.png)

**Comment by SchulzeStTSI** [comment]
@RalicaY @chrloch The code contains a additional field "dp" which is not defined in https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/main/DCC.Types.schema.json#L9 Can you please check, why they add this?

**Comment by RalicaY** [comment]
@chrloch ,  do you know more about this additional field "dp"? 
{
  "dob" : "1996-10-11",
  "nam" : {
    "gn" : "ԼԻԼԻԹ",
    "fnt" : "KHACHATRYAN",
    "gnt" : "LILIT",
    "fn" : "ԽԱՉԱՏՐՅԱՆ"
  },
  "ver" : "1.3.0",
  "v" : [
    {
      "tg" : "840539006",
      "is" : "Ministry of Health of the Armenia Republic",
      "co" : "AM",
      "mp" : "EU\/1\/21\/1529",
      "sd" : 1,
      "dp" : 1,
      "dt" : "2021-06-15",
      "ma" : "ORG-100001699",
      "vp" : "1119349007",
      "ci" : "URN:UVCI:01:AM:d5690263a54f526ca675424c599e45054ddf441ab6b4c996",
      "dn" : 1
    }
  ]
}

**Comment by chrloch** [comment]
Additional fields are allowed by the schema and we have agreed that verifiers should ignore them.
Still, I'm also curious what the field means. I'll contact the issuers.

**Comment by oleksandrsarapulovgl** [comment]
PR with fix: https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/66

**Comment by RalicaY** [comment]
Successfully retested,
Verifier App 1.2.4-acc (28)
Galaxy XCover 4, Android 9
