### ISSUE TITLE
[Android] Anonymisation of the Shared Data Seems to Be Random 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#223]
## Describe the bug
Anonymisation of the shared data seems to be random: certain personal data is sent  anonymised although no option for anonymisation is set.  Whether the data gets sent anonymised or not is currently depending on the certificate's type and the debug level which has been set.  Yet, here as well, there is no uniform approach. 

## Technical details
Android Verifier 1.2.0-RC-1

**Comment by MykhailoNester** [comment]
When debug mode ON in settings default level of anonymization selected - `Level 1 - normal capture`
You can switch to level 2/3.
But when generate zip file from one certificate two times it should generate same result.

**Comment by MykhailoNester** [comment]
Preconditions:
select:
- Debug mode ON in settings
- Level 1 - normal capture
- select country: de, ua.
- Validate with: Ukraine

![device-2021-09-28-122941](https://user-images.githubusercontent.com/9447674/135064259-94a23f85-dcbe-4a48-87d8-96a2f8c08ae9.png)

STR for vaccination Level 1.:
Scan this QR code with date in future.

<img width="300" alt="date_in_future" src="https://user-images.githubusercontent.com/9447674/135064480-dea3d835-ce25-4fcd-a035-2fd650c284a6.png">

Share zip file:
JSON structure of `payload.json` should be:

```
{
   "dateOfBirth":"1990-99-99",
   "person":{
      "familyName":"Xxxxxx",
      "givenName":"Xxxxxxxx",
      "standardisedFamilyName":"XXXXXX",
      "standardisedGivenName":"XXXXXXXX"
   },
   "recoveryStatements":null,
   "tests":null,
   "vaccinations":[
      {
         "certificateIdentifier":"URN:UVCI:V1:DE:XXXXXXXXXXXXXXXXXXXXXXXXXX",
         "certificateIssuer":"UK",
         "countryOfVaccination":"UA",
         "dateOfVaccination":"2021-10-27",
         "disease":"COVID_19",
         "doseNumber":1,
         "manufacturer":"ORG-100031184",
         "medicinalProduct":"EU/1/20/1507",
         "totalSeriesOfDoses":2,
         "vaccine":"J07BX03"
      }
   ],
   "fullName":"Xxxxxxxx Xxxxxx"
}
```

For level 2 - traceable capture:

```
{
   "dateOfBirth":"1990-99-99",
   "person":{
      "familyName":"Xxxxxx",
      "givenName":"Xxxxxxxx",
      "standardisedFamilyName":"XXXXXX",
      "standardisedGivenName":"XXXXXXXX"
   },
   "recoveryStatements":null,
   "tests":null,
   "vaccinations":[
      {
         "certificateIdentifier":"URN:UVCI:V1:DE:D0B1Q4VXDPGUVIWHA99FGY34OC",
         "certificateIssuer":"UK",
         "countryOfVaccination":"UA",
         "dateOfVaccination":"2021-10-27",
         "disease":"COVID_19",
         "doseNumber":1,
         "manufacturer":"ORG-100031184",
         "medicinalProduct":"EU/1/20/1507",
         "totalSeriesOfDoses":2,
         "vaccine":"J07BX03"
      }
   ],
   "fullName":"Xxxxxxxx Xxxxxx"
}
```

Level 3 - full take:

```
{
   "dateOfBirth":"1990-01-01",
   "person":{
      "familyName":"Nester",
      "givenName":"Mykhailo",
      "standardisedFamilyName":"NESTER",
      "standardisedGivenName":"MYKHAILO"
   },
   "recoveryStatements":null,
   "tests":null,
   "vaccinations":[
      {
         "certificateIdentifier":"URN:UVCI:V1:DE:D0B1Q4VXDPGUVIWHA99FGY34OC",
         "certificateIssuer":"UK",
         "countryOfVaccination":"UA",
         "dateOfVaccination":"2021-10-27",
         "disease":"COVID_19",
         "doseNumber":1,
         "manufacturer":"ORG-100031184",
         "medicinalProduct":"EU/1/20/1507",
         "totalSeriesOfDoses":2,
         "vaccine":"J07BX03"
      }
   ],
   "fullName":"Mykhailo Nester"
}
```

**Comment by ltranvan** [comment]
After discussion with Steffen S. (Author of the SPEC-document) and Hendrik (development) following resolution:
- Anonymization option is coupled to the debug mode option. (means there is no extra option for anoynmization).
- Anonymization is only used for personal data in the shared files only for debug level 1 and level 2.
-So in case that the software is implemented correctly as described above, it is then correct and the ticket can be closed.

**Comment by RalicaY** [comment]
Successfully retested,
Verifier App 1.2.4-acc (28)
Galaxy XCover 4, Android 9
