### ISSUE TITLE
Where are the pubKeys

### ISSUE THREAD

**Issue by igmer** [eu-digital-green-certificates/dgca-verifier-app-android#243]
## Your Question

Where are the pubKeys? I have a config.json file, in this file I need to put the keys but I don't understand where I can find them
 
         "pubKeys": [
              "lKdU1EbQubxyDDm2q3N8KclZ2C94Num3xXjG0pk+3eI=",
              "r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="
           ]

* Source File:
* Line(s):
* Question:

**Comment by daniel-eder** [comment]
Please see https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
