### ISSUE TITLE
Italy is overriding the Green Certificate for international mobility by asking a test to enter the country, ignoring the green certificate

### ISSUE THREAD

**Issue by loic86** [eu-digital-green-certificates/dgca-verifier-app-android#248]
Hi,
Italy is now restricting the policy of the "green certificate", called "green pass" there, to just the "2G" rules, completely removing the article 6 of the [Regulation (EU) 2021/953](https://eur-lex.europa.eu/legal-content/EN/TXT/?toc=OJ%3AL%3A2021%3A211%3ATOC&uri=uriserv%3AOJ.L_.2021.211.01.0001.01.ENG), the rule that create this tool.
If this is not enough, then the Italian government, to prove that didn't understand the goal of this "green certificate" is now **asking a test to all the travelers entering the country, overriding the primary goal of the Green Certificate**! (the naming into "green pass" was already a big red flag, indeed, if you want to laugh: now they "discovered" that if a vaccinated green pass holder is positive is still passing the proof, thinking that this feature is instead a bug. Of course this "bug" is used to convince people to the need of implementing the revocation, still something that the regulation warns to limit).
This rule is completely overruling the stated goal of your green certificate, so what are we doing?
To summarize, in Italy now this is the situation:

1.  **For international mobility, the stated goal of the Green Certificate, is now overridden by asking a test for every traveler entering the country, no matter if he is already holding a valid green certificate.**
2. The Green Certificate is used for every social activity, but restricted to 2G policy (aka "Super Green Pass").
3. The "Classic Green Certificate" is used for the right to work, with the possibility of proof of test (the certificate is mandatory if you want to work. is that proportional?)

Is that a normal situation, a scenario that you were expecting when you started the development? Do you still think that this concern is just a sophism that should not be asked to the engineers, architects and developers? Are you not afraid of the path that we are taking? 
At least now you understand that when you try to "improve the certificate to avoid frauds" the fraudsters are not "lazy travelers" that are not doing a "one-off test", but instead desperate people that see their lives and dignity ruined from these mad implementations of the member states?

**Comment by daniel-eder** [comment]
Hi loic86,

Our stance in regard to this not being a platform for political discussion is unchanged.
To avoid duplication, please also see my latest comment on https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/247#issuecomment-997663087 that elaborates a bit further on this.
