### ISSUE TITLE
Janssen Booster Covid Certificates fail verification

### ISSUE THREAD

**Issue by stoconnor** [eu-digital-green-certificates/dgca-verifier-app-android#264]
Booster certificates where the original vaccine was Janssen fails verification.

The Digital Covid Certificate appears as 2 of 1 doses. Number of doses is 2 and Total doses is 1 where it refers to the booster.

The certificate is as per European recommendation set out here:

https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837

"Boosters will be recorded as follows:

3/3 for a booster dose following a primary 2-dose vaccination series.
2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person"

**Comment by kerstin-oppermann-tsi** [comment]
@stoconnor is this relevant anymore? If yes can you provide screenshot for this. For me it is working with Janssen 2/1. 
![image](https://user-images.githubusercontent.com/81565834/160810537-3f74a815-c649-42c6-9ea0-9fa4c6889ff4.png)

**Comment by stoconnor** [comment]
Re-tested this and it's working for me also. Thanks! Closing issue 👍 🚀
