### ISSUE TITLE
[Android-Verifier-App] Certificates still Evaluated as "Revoked" after Deletion of Revocation Entry 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#285]
The following Certificate gets evaluated as "revoked" although its  corresponding revocation entry was deleted from the gateway.

## Expected behaviour

The certificate must be evaluated as "valid".

![VAC_B12](https://user-images.githubusercontent.com/76050122/155193715-17e86d70-3679-4203-b70d-ab890c51712b.png)

## Technical Details
Galaxy XCover 4, Android 9
DGCA Verifier for Android, Version: 1.2.4-without-signature-verification-tst (34)

**Comment by MykhailoNester** [comment]
@RalicaY  could you test today once more? 
Application synchronizes once per day. I tested it today and it shows `Cryptographic signature invalid` because it is version without `signature-verification`

**Comment by RalicaY** [comment]
@MykhailoNester  Today  (scanned at 11:02, 23. Feb, 22) it is still shown as "revoked".

**Comment by MykhailoNester** [comment]
Tested again when data on device reloaded was able to reproduce it `revoked` on my device as well.


Revocation validation flow:
SIGNATURE Hash: **8bd49e3565a239494acb0f7c17e58f40**
Slice found: 
DccRevocationSlice(sid=**e13c98433f85838457844197c55f12ce9ac2835b0a131599cd845ed966d3fddf**, kid=/JdNkm+G0Fg=, x=null, y=null, cid=8, type=BLOOMFILTER, version=1.0, expires=2023-02-18T15:00Z, content=[0, 1, 44, 0, 43, -116, -68, -52, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, -34, -17, 113, 50, 9, 27, -77, 34])

Dcc revoked bloomfilter: **8bd49e3565a239494acb0f7c17e58f40**


In response for:
GET /lists/_JdNkm-G0Fg/partitions

we receive this chunk with the same slice ID:

"8":{"2023-02-18T15:00:00Z":{"type":"BLOOMFILTER","version":"1.0","hash":"**e13c98433f85838457844197c55f12ce9ac2835b0a131599cd845ed966d3fddf**"}}


So with latest API data behaviour is correct.

**Comment by RalicaY** [comment]
Successfully retested.
