### ISSUE TITLE
[Android Verifier App] Local Delete Workflow for Expired Revocations on Verifier App does Not Start Automatically 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#288]
Local Delete Workflow for Expired Revocations on Verifier App does not start automatically even after more than 24 hours offline (internet switched off) although according to the specification ( (Verfier Workflow, Spec. Chapter 1.3 "Delete expired revocation entries") it should take place.
 

## Describe the bug
1)  Verifier  was newly installed on 28.02.2022 at  11:40  -> Then, we scanned and the following certificate was shown correctly as revoked;
2)  28.02.2022 at  11:41 we switched OFF the internet on the verifier device; 
3) We waited 24 hours and in the meantime the revocation entry for the given certificate has already expired. ( 'expires': '2022-03-01T09:30:00Z')
4)  Then (after more than 24 hours)  01.03.2022  at 12:40 (internet still switched OFF) we scanned again the same certificate --> certificate  was incorrectly still shown as revoked. (Expectation was that it would be shown valid). 
## Expected behaviour:
Verifier should locally recognize certificate as valid within 24 hours  (Verfier Workflow, Spec. Chapter 1.3 "Delete expired revocation entries")
 
## Technical Details:
Verifier for Android, Version 1.2.4-tst (36)
![VAC_Batch13](https://user-images.githubusercontent.com/76050122/156176085-cbf91371-beec-4d8b-8f3e-330fba69ba3a.png)

https://user-images.githubusercontent.com/76050122/156176141-723fd181-360b-4b65-ae39-c5ab2b8ea4cd.mp4

**Comment by MykhailoNester** [comment]
Code that fixes this issue was added on 9.03.2022. So probably it is already fixed. 
Found one issue with time during downloading process. I'll prepare PR with changes. 
Another issue related to `eTag` when we receive 304 code `eTag` was removed and cause next api calls to fail.
  
Additionally added in settings page time of last revocation sync. and button to refresh data.
When you press reload button time should be updated to you device time when successfully updated. Otherwise the was error during update flow.

<img width="220" alt="Screenshot 2022-03-24 at 22 56 51" src="https://user-images.githubusercontent.com/9447674/160008931-b9b56d64-670d-4982-ae06-24a55eab767f.png">

PR:
https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/296

**Comment by RalicaY** [comment]
@MykhailoNester, thank you very much!
@ltranvan @Hendrik-Schmidt-Schierhorn-TSI, can we get this PR merged in a new release for testing?

**Comment by ltranvan** [comment]
from my point of view (testing) asap for test. Please for both version: Bloomfilter AND Hash-List. 
@Hendrik-Schmidt-Schierhorn-TSI and you?

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY can you please retest with newest release Version 1.3.1-tst (46)

**Comment by RalicaY** [comment]
@MykhailoNester We have the situation where the verifier is standalone (no internet).
Our question: when does exactly the Verfier-WorkFlow take place, so that it looks in its own local  app Revocations-DB which entries are already expired and that it knows that they must be deleted from the revocation list? Is this a synchronous event or is it triggered by some process? If it is synchronous at what intervals -- daily, hourly? Or is there some trigger and what is this trigger based on?
We need this information to check, that exactly at this point in time the standalone verifier will validate a QR-Code with an expired revocation entry as valid again.
Your help and elaboration on this is much appreciated!

**Comment by MykhailoNester** [comment]
@RalicaY 
The flow is next:
- On fresh install when user launches app it will start sycnhronization process which loads all keys etc. and revocation data. It will also schedule worker that responsible for next sync. this worker has constraints it will start once per DAY and internet connection should be connected. It means there is no exact time when sync. happens but it will be close to the hour when first sync. was initiated. When connection restored it will trigger sync. in case 24hours gone.
- On each sync. event app will check expiration dates and remove outdated.
- On each app launch - `cold launch` app will check expiration and remove outdated even without network connection.

**Comment by MykhailoNester** [comment]
To check if revocation data was updated by worker you can open settings to see `last updated time` close to revocation data update button.

**Comment by RalicaY** [comment]
Successfully retested for Version 1.2.4-tst (43) and Version 1.3.1-tst (46)
