### ISSUE TITLE
[ACC] Revocation fails for ES

### ISSUE THREAD

**Issue by chrloch** [eu-digital-green-certificates/dgca-verifier-app-android#291]
## Description
We have revoked sample codes from DE and from ES.
DE QR codes are correctly displayed as revoked when scanned.
ES QR codes are shown as valid although revocation batch exists on ACC

## Expected behaviour

Revoked QR codes should appear as revoked

## Steps to reproduce the issue

Go to https://github.com/eu-digital-green-certificates/dcc-quality-assurance/pull/289/files
Scan the QR codes.
They will appear as "revoked"

Go to https://github.com/eu-digital-green-certificates/dcc-quality-assurance/pull/291/files
Scan the QR codes. 
They appear as valid

## Additional context

The ES revocation was uploaded for all 3 possible hash types. 
We have successfully downloaded the ES revocation batches and have calculated the hashes again with the same tool that we had used for the creation of the DE batches

HashType | downloaded from Gateway | calculated with our tool
------------|------------------------------|----------------------------
UCI  | dNImhq2X3oucVgB/BFzWqQ==  |  dNImhq2X3oucVgB/BFzWqQ==
UCI  |P4nd4fPW4wjQOqv8VWdxBw== | P4nd4fPW4wjQOqv8VWdxBw==
COUNTRYCODEUCI| 1mezczKV+kEAWCO/OvGCIQ== | 1mezczKV+kEAWCO/OvGCIQ==
COUNTRYCODEUCI | 8UkOPm68IaJFL7Bmk+VULw==  | 8UkOPm68IaJFL7Bmk+VULw==
SIGNATURE | Iv6IF+ZY4jHSKJGoJTGtZw==  | Iv6IF+ZY4jHSKJGoJTGtZw==
SIGNATURE | 1Zb/UkR8IxVakSB/NoZS/A== | 1Zb/UkR8IxVakSB/NoZS/A==

### Batches on ACC: 
ID | Country | timestamp | deleted
-|-|-|-
d9e1b534-3f66-44d1-9776-18ca9ba8b0ef  |  ES   |   2022-03-01T18:59:14+01:00 |       False
793ca1ac-f79f-4194-b1de-a7f63cc307b1   | ES    |  2022-03-02T00:59:22+01:00    |   False
b4ef3aca-5446-420e-8764-4a2635f51e9b  |  ES  |    2022-03-02T06:59:28+01:00   |    False
58fdc85a-d95e-411b-8c83-5ea8e4da56ce  |  ES |     2022-03-02T10:35:42+01:00   |    False
175cc1f5-f938-41d0-a151-a0004ddfc39c   | ES |     2022-03-02T10:46:20+01:00    |   False

**Comment by MykhailoNester** [comment]
Hi @chrloch

For DE certificate. `Signature` type hash was found in one slice. So result is `certificate revoked`. Logs:

```
Revocation check start
SIGNATURE Hash: ef476f527e985c204e7e170eb892f375
Slice found: DccRevocationSlice(sid=3a87462201e5c634a8da31ebbddd48e703fd65e3119f9466a5c07c2b5ef40b34, kid=9cWXDDA52FQ=, x=null, y=null, cid=e, type=BLOOMFILTER, version=1.0, expires=2023-03-01T11:00Z, content=[0, 1, 67, 0, 43, -116, -68, -52, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 6, 89, 8, 71, -108, 85, 61, -43, -43, -121, 49, 64, 41, -68, -77, -111, -72, -42, 51, -90, 69, -90, 42, -126, 126])
dcc revoked bloomfilter: ef476f527e985c204e7e170eb892f375
Revocation check end. uci:false, co+uci:false, signature:true
```

And for `ES` certificate revocation flow fails on first step where we check KID metadata: `B4BbJQx1lYQ=` no such KID in database.

Available KIDs from backend:

```
[
   {
      "kid":"9cWXDDA52FQ=",
      "mode":"POINT",
      "hashTypes":[
         "SIGNATURE"
      ],
      "expires":"2023-03-01T11:00:00Z",
      "lastUpdated":"2022-03-04T16:08:49Z"
   },
   {
      "kid":"zMq8VEXlueo=",
      "mode":"POINT",
      "hashTypes":[
         "SIGNATURE"
      ],
      "expires":"2022-07-28T21:00:00Z",
      "lastUpdated":"2022-03-04T16:08:45Z"
   },
   {
      "kid":"iWk60lLc9eY=",
      "mode":"POINT",
      "hashTypes":[
         "SIGNATURE"
      ],
      "expires":"2022-03-10T12:00:00Z",
      "lastUpdated":"2022-03-06T16:28:57Z"
   },
   {
      "kid":"/JdNkm+G0Fg=",
      "mode":"POINT",
      "hashTypes":[
         "COUNTRYCODEUCI",
         "SIGNATURE",
         "UCI"
      ],
      "expires":"2023-02-18T15:00:00Z",
      "lastUpdated":"2022-03-04T16:08:38Z"
   },
   {
      "kid":"VpHthrJRPZU=",
      "mode":"POINT",
      "hashTypes":[
         "COUNTRYCODEUCI",
         "SIGNATURE",
         "UCI"
      ],
      "expires":"2023-03-07T19:00:00Z",
      "lastUpdated":"2022-03-08T08:59:22Z"
   },
   {
      "kid":"GSXuNoyWGYo=",
      "mode":"POINT",
      "hashTypes":[
         "UCI"
      ],
      "expires":"2023-11-27T10:15:14Z",
      "lastUpdated":"2022-03-04T16:08:55Z"
   }
]
 ```

**Comment by chrloch** [comment]
Hi @MykhailoNester 

do you use a different database in the revocation service than for the verification? 
The KID `B4BbJQx1lYQ=` is on the gateway and the Verifier App can get it from its backend because it validates the DCCs as green which are signed with it.

**Comment by chrloch** [comment]
The Batches seem to be missing in the validation service
