### ISSUE TITLE
[Android-Verifier-App] Scanning of QR-Codes Not Possible

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#301]
## Describe the bug

When I scan a QR Code, I get the error:  "Diese Aktion kann von keiner App ausgeführt werden". (see attached video)

## Technical Details
Android Verifier App Version 1.3.1-tst (51)
Galaxy XCover 4, Android 9

https://user-images.githubusercontent.com/76050122/163171691-d10c4024-a295-4074-82db-29e401bee402.mp4

**Comment by RalicaY** [comment]
@MykhailoNester We have found out, that this happens only on certain older devices in comnination with having additionally installed the DGCA wallet app together with the verifier app on the same device.  When we deinstalled the wallet app, the issue disappeared and the verifier app worked correctly.

**Comment by MykhailoNester** [comment]
Fix available in build: 1.3.2-tst-hash (60)

**Comment by MykhailoNester** [comment]
Latest build: 1.3.2 (61)

**Comment by RalicaY** [comment]
Successfully retested 1.3.2(61)
