### ISSUE TITLE
[Android-Verifier-App] Updating IssuerList is Not Possible

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#303]
## Describe the bug
There is no possibility to update the issuer list in the Verifiable Credentials (VC) area.  See attached Video.

## Technical details
Verifier App for Android Hash List Version 1.4.0 (54) and Verifier App for Android Bloom Filter Version 1.4.0 (53)

https://user-images.githubusercontent.com/76050122/164453974-3621e0bb-0407-4758-bb01-174230ed5f32.mp4

**Comment by MykhailoNester** [comment]
For now I removed this empty settings page for VC. Discussed it with Hendrik and also Steffen mention that it is not must have feature. But it is good have this. So we can convert this `bug` ticket into `task` and implement as soon as all high prio tasks will be completed.

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY you can check this is version 1.3.2(61)

**Comment by RalicaY** [comment]
Successfully retested for Android Verifier 1.3.2 (61) Hash

**Comment by ltranvan** [comment]
tvt, 10.05.2022: additional info:  Retest successfully with Verifier 1.3.2(61) (Bloom-version!).
