### ISSUE TITLE
[Android-Verifier-App] App Crashed after reading a JWT with a Null Value 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#304]
## Describe the bug

App crashed after scanning a JWT with a null value in nbf.

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by MykhailoNester** [comment]
@RalicaY Fixed in 
1.4.1-tst-hash (55)(56) builds

**Comment by RalicaY** [comment]
Sucessful  retest Android Verifier 1.4.1-tst-bloom (56) and Version 1.4.1-tst-hash (55)
