### ISSUE TITLE
[Android Verifier App] Granting Consent to Issuer not in IssuerList leads to Invalid Signature

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#305]
## Describe the bug

We scanned the following Claim whose Issuer was not on the App's IssuerList.  The app correctly recognized this fact and asked us whether we want to grant consent.  After granting consent the JWT wa still evaluated as invalid. The issue exists both for Hash and Bloom Filter versions.  See attached video.

## Expected behaviour

The trust issuer for which the consent was granted must be added in the local app's database after the consent was granted. 
## Technical details
Version 1.4.0-tst-bloom (53)
Version 1.4.0-tst-hash (54)
![private_issuer](https://user-images.githubusercontent.com/76050122/164683892-0d1934b5-9e02-40e5-be45-51e88447bc42.png)
![invalid_signature](https://user-images.githubusercontent.com/76050122/164683944-f2359cdc-a94c-401c-8211-43d3b7323c93.png)

https://user-images.githubusercontent.com/76050122/164684712-49ec64ff-4127-4348-b171-83ae4809ee68.mp4

**Comment by MykhailoNester** [comment]
@RalicaY 
Issuer in QR: https://files.emilina.de/dcctestdata/my-issuer
Resolved: https://files.emilina.de/dcctestdata/my-issuer/.well-known/did.json

when you open resolved url it show 404 error so no valid jwk for signature check as a result it is invalid signature error.

**Comment by MykhailoNester** [comment]
I found issue it is related to JWK optional/required fields.
Will be fixed in next version.

**Comment by chrloch** [comment]
If we have documented which fields in a JWK are expected, we can also adapt the JWKS - but it needs to be documented what fields the app needs :-)

**Comment by MykhailoNester** [comment]
@chrloch for now only `kty` and `kid` required

**Comment by MykhailoNester** [comment]
Fixed in build: 1.4.1-tst-bloom (55) (56)

**Comment by RalicaY** [comment]
Successfully tested, Android Verifier  1.4.1-tst-bloom (56) and Version 1.4.1-tst-hash (55)
