### ISSUE TITLE
[Android Verifier App] Consent Grant is Asked For On Second Scanning Although Consent Had Been Granted On Previous Scan Already

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#307]
## Describe the bug

We scanned a Verifiable Credential whose issuer was not on the Issuers' List and granted consent. This way, we could successfully read the Verifiable Credential's data.

Then, we scanned the same Verifiable Credential again -- the app asked us again for consent (although we had already granted consent at the first time when we scanned).

## Expected Behaviour
Once we have granted consent for the same Issuer, the app should not ask us again, because the Issuer must have been already saved in its local database after the first consent was granted.

## Technical Details
Android Verifier 1.4.1-tst-bloom (56) and Version 1.4.1-tst-hash (55)

**Comment by MykhailoNester** [comment]
Fixed in 1.4.2 (57)(58)

**Comment by MykhailoNester** [comment]
Latest build: 1.3.2 (61)

**Comment by ltranvan** [comment]
tvt, 04.05.2022: pos. retested with HASH-Verion (tvt) and Bloom-Version (Ralica).
