### ISSUE TITLE
[Android-Verifier-App] Fulfilled Business Rule is Evaluated as OPEN

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#311]
## Describe the bug

We have scanned a Vac DCC to test the Business Rule VR-DX-0004.  We scanned a certificate (see attached cert) where the birthdate is  01.01.2010.  Since the person is less than 18 years old as of today , in accordance with the rule, the Grundimmunisation is still valid and does not expire after a certain MAX number of days.  This is why the rule must evaluate as truel

Nevertheless, the verifier app evaluates the rule as "OPEN".

## Additional Info
Since the rule was uploaded today and will be active only in 48 hours from now, we set the device's time to 48 hours in the future to be able to see the rule.

## Expected behaviour
The rule is fulfilled (valid).

## Technical details
Verifier App 1.3.2 -tst - hash & bloom (61)
![open_rule](https://user-images.githubusercontent.com/76050122/166679275-5289c80d-1d73-43bf-bba6-0497a9916e53.png)
![vac](https://user-images.githubusercontent.com/76050122/166679390-c63f8a58-bada-4607-8c07-92301c696649.png)

**Comment by ltranvan** [comment]
INF: Ticket blocks currently all test cases for checking VR4-BR with the new cert-logic applied on birthdate field.

**Comment by ltranvan** [comment]
Retest successfully caried out.
