### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by niwla23** [eu-digital-green-certificates/dgca-verifier-app-android#34]
## Describe the bug
I am unable to build this app on manjaro linux

## Expected behaviour
App should build properly

## Steps to reproduce the issue

1. Clone the repo
2. Run ./gradlew build
3. This error appears:
```
Could not determine the dependencies of task ':app:lintRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :decoder.
     Required by:
         project :app
      > No matching configuration of project :decoder was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.
```

## Technical details

- Host Machine OS (Windows/Linux/Mac): Manjaro Linux

**Comment by niwla23** [comment]
Same problem for dgca-wallet-app-android

**Comment by oleksandrsarapulovgl** [comment]
To make it compiled - you need to have core repository on the same level as verifier/wallet: https://github.com/eu-digital-green-certificates/dgca-app-core-android

**Comment by andypandy47** [comment]
@oleksandrsarapulovgl that sorted it for me. I struggled with this for quite a while!

I've created a branch to update the build section of the readme with this info but don't have permissions to push to the repo. Can someone update the readme or give me permissions to contribute?

Thanks

**Comment by daniel-eder** [comment]
> @oleksandrsarapulovgl that sorted it for me. I struggled with this for quite a while!
> 
> I've created a branch to update the build section of the readme with this info but don't have permissions to push to the repo. Can someone update the readme or give me permissions to contribute?
> 
> Thanks

@andypandy47 can you create a pull request from your fork?

**Comment by andypandy47** [comment]
Ah right, sorry I haven't contributed to a repo before so wasn't aware I had to create my own fork. Have sorted it now though, PR can be found [here](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/42)
