### ISSUE TITLE
Handling of Key Identifiers During Verification Violates Specification

### ISSUE THREAD

**Issue by fneur** [eu-digital-green-certificates/dgca-verifier-app-android#35]
## Describe the bug

The handling of Key Identifiers (_kid_) during verification violates the following requirement of Sec. 3.3.3 of the
[specification](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf):

> _Due to the shortening of the identifier (for space-preserving reasons) there is a slim but nonfinite chance that
> the overall list of DSCs accepted by a validator may contain DSCs with duplicate _kids_. For this reason a verifier
> MUST check all DSCs with that _kid_._
> 

However, given two or more DSCs with the same _kid_,  the code in VerificationViewModel.kt (cf. `decode` function) does not  check all DSCs with that kid (but only one, possibly the wrong one) during certificate verification:

```
val kid = coseData.kid
...
val certificate = verifierRepository.getCertificate(kid.toBase64())
if (certificate == null) {
  Timber.d("Verification failed: failed to load certificate")
  return@withContext
}
cryptoService.validate(cose, certificate, verificationResult)
```

## Expected behaviour
Correct handling of DSCs with duplicate _kids_ in accordance with the specification.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/38

**Comment by oleksandrsarapulovgl** [comment]
Closed with PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/38
