### ISSUE TITLE
In case of a failed verification (RED), the app should only display the reason for the fail

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#39]
## Describe the bug
Despite a failed verification, the verifier app shows the certificate data set and no reason for failure is shown.

## Expected behaviour

In case of a failed verification (RED), the app should only display the reason for the fail.

## Steps to reproduce the issue
1. Open verifier app;
2. Scan a QR-Code for an invalid certificate.

## Technical details

Galaxy XCover 4, Modellnummer: SM-G390F,
Android-Version: 9, Verifier App 1.0.0

**Comment by ltranvan** [comment]
Additional info: This behaviour decribed above occures just only for Android-VerifierApp. 
IOS-VerifierApp shows only the reason(s) of the failed check (without showing any further datas of the vaccination and the vaccinated person).

**Comment by oleksandrsarapulovgl** [comment]
@ltranvan could you please provide specific QRs and specific expected errors to be displayed?

**Comment by ltranvan** [comment]
> @ltranvan could you please provide specific QRs and specific expected errors to be displayed?

I have ask Ralica to give you the info needed. But in generel i would expect that Android would list the same error message as dieplayed by IOS,isn't it?

**Comment by RalicaY** [comment]
![QR_TestPositive](https://user-images.githubusercontent.com/76050122/119028040-4b5d1300-b9a7-11eb-8bf4-3d5b9c4272f5.png)

**Comment by RalicaY** [comment]
This Certificate is invalid.  The reason is: "The test result is positive."

**Comment by RalicaY** [comment]
![iOS_Verifier](https://user-images.githubusercontent.com/76050122/119028334-a131bb00-b9a7-11eb-8a7b-a3cd68e8358e.jpg)

After scanning the above invalid QR Code with the iOS Verifier App -- the reason for invalidation is displayed: "The test result is positive."

**Comment by RalicaY** [comment]
Other specific Errors to be displayed are: "The cryptographic Signature is invalid.", "The test date is in the future", etc.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/48

**Comment by oleksandrsarapulovgl** [comment]
PRs:
https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/66
https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/19

**Comment by kerstin-oppermann-tsi** [comment]
![image](https://user-images.githubusercontent.com/81565834/122370168-25ec0680-cf5f-11eb-8515-d1e23fceba32.png)
retested in release 1.0.5
