### ISSUE TITLE
Cryptographic signature invalid error

### ISSUE THREAD

**Issue by digitalmind** [eu-digital-green-certificates/dgca-verifier-app-android#54]
## While testing, I keep getting cryptographic signature invalid error. 

The test url is [https://user-images.githubusercontent.com/76050122/119028040-4b5d1300-b9a7-11eb-8bf4-3d5b9c4272f5.png](https://user-images.githubusercontent.com/76050122/119028040-4b5d1300-b9a7-11eb-8bf4-3d5b9c4272f5.png)
I have tried updating the public keys but that did not change anything. Upon inspection I can see that the signer certificate update results in a 204 response.
 204 No Content https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com/signercertificateUpdate (126ms)

I have tested signer certificate url in POSTMAN and the response is 200.

ps. The ios version works normally

What am I missing?

**Comment by RalicaY** [comment]
Hello, it is seems to be a bug connected to the fact that the Test Result in the QR-Code has the value "DETECTED".  You should try with a QR Code with Test Result Value of "UNDECTED".

**Comment by digitalmind** [comment]
Thank you
