### ISSUE TITLE
[Android] QR-Codes of type TEST with "TEST Result = Detected" are evaluated as cryptographically invalid.

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#55]
## Describe the bug

QR-Code of type TEST with TEST Result = Detected  are evaluated as cryptographically invalid.

## Expected behaviour

QR-Code of type TEST with TEST Result = Detected should evaluate to invalid with reason "Test result positive" and the affected part of the dataset incl. "test result = DETECTED" should be shown.

## Steps to reproduce the issue

Scan a QR-Code of Type Test with TEST RESULT = DETECTED

## Technical details
Galaxy XCover 4, Modellnummer: SM-G390F,
Android-Version: 9,

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY Could you please share QR code to reproduce it?

**Comment by RalicaY** [comment]
Exactly the same example as above but only TEST RESULT = NOT DETECTED 
![Example_Not_detected](https://user-images.githubusercontent.com/76050122/119949849-91633980-bf9a-11eb-958f-73354d88966a.png)

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl , just as additional info: in both of the above examples, all optional fields were filled with data.  No optional fields were left empty.

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl, we expect that in the first example where COVID is DETECTED, that it would be invalid with displayed reason: "Test result positive" and the data set that refers to the positive result would be displayed also in accordance with the specification: "In case of a failed verification (RED), the app should only display the reason for the fail, including details such as the specific contents or technical details of the certificate that are preventing the successful verification"

**Comment by oleksandrsarapulovgl** [comment]
@Hendrik-Schmidt-Schierhorn-TSI could you please confirm required changes?

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY by the way, is there a chance you could share a screenshot or design of how proper displaying would be shown? Maybe from iOS application?

**Comment by oleksandrsarapulovgl** [comment]
PRs:
https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/66
https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/19

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY Could you please clarify the right text for  test result is positive problem?

In this ticket you wrote: "Test result positive", but in this: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/39 - "The test result is positive.".


Could you please clarify which one to use?

**Comment by RalicaY** [comment]
Test result positive

**Comment by kerstin-oppermann-tsi** [comment]
![image](https://user-images.githubusercontent.com/81565834/122369232-4bc4db80-cf5e-11eb-80a9-413a1e1203b6.png)
fixed, retested in release 1.0.5
