### ISSUE TITLE
[Android] Field "Country of Vaccination" should be named "Issuer Country"

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#62]
## Describe the bug

Currently the field "Country of Vaccination" is seen in the Data Set of all Certificate Types -- VAC, TEST and REC.  It makes sense only for Vac, but not for TEST and REC.

## Expected behaviour

The field "Country of Vaccination" should be renamed to "Issuer Country".
![country_of_vaccination](https://user-images.githubusercontent.com/76050122/120063985-46185c00-c06a-11eb-9b17-528976b10189.png)

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY could you please clarify, we should show "Issuer Country" for all types: vacc, rec, test?

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/64

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl yes, for all three types VAC, REC and TEST it should read "Issuer Country".

**Comment by kerstin-oppermann-tsi** [comment]
Fixed and tested in release 1.0.5
