### ISSUE TITLE
[Android] The application crashes when I try to scan the QR codes of Germany

### ISSUE THREAD

**Issue by skounis** [eu-digital-green-certificates/dgca-verifier-app-android#63]
## Describe the bug
I try to scan the QR codes Germany updated by using the `v1.0.1` build (.apk)

- https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/DE

## Steps to reproduce the issue
1. Download and Install the `.apk`
2. Scan the QR codes uploaded by Germany https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/DE
3. The application collapses and goes away without any message. 

## Technical details

- Host Machine OS (Windows/Linux/Mac): Android Pixel 2

**Comment by oleksandrsarapulovgl** [comment]
I tested, and non of DE QRs crashes for me. Could you please share here the link to specific example?

I think it has been fixed in some of recent changes

**Comment by tdinckaya** [comment]
I think, signercertificateUpdate api service returned 204 No Content and  signercertificateStatus service returned empty array. For this reason, the crash may have occurred

**Comment by skounis** [comment]
@oleksandrsarapulovgl please note that the ticket refers to `v1.0.1`. I just checked with the `v1.0.2` build and it scans them.

**Comment by oleksandrsarapulovgl** [comment]
Thank you @tdinckaya @skounis ! So, that what I suspected. That is should have been fixed in next release
