### ISSUE TITLE
[Android] Value of field of "Disease or Agent Targeted" should be humanly readable

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-android#68]
## Describe the bug

The Value of the field "Disease or Agent Targeted" should be humanly readable and not a number.  In the attached example the value should read "Covid-19" instead of 840539006.

![agent](https://user-images.githubusercontent.com/76050122/120344225-b12b9200-c2f9-11eb-91f0-80b928de3f14.png)

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY could you please help me, do you have the full list of disease codes we could expect, it's clear that receiving "840539006" we need to show Covid-19. But what if we receive other number code: should we show "Undefined" or something? Or do we have list of all possible codes?

**Comment by RalicaY** [comment]
@ltranvan can you provide additional information on this?

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY could you please clarify, is it look right: 
![Screenshot_1622717349](https://user-images.githubusercontent.com/82441124/120633261-9e889880-c472-11eb-9f62-c35338c34190.png)

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/75

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl yes

**Comment by RalicaY** [comment]
Successfully retested with Verifier 1.1.2-tst ( bar for Belgium, with this country selected, the app crashes. This is being analysed and a new ticket will be created for this problem)
