### ISSUE TITLE
Scanning a random unrelated QR code shows confusing message

### ISSUE THREAD

**Issue by Leseratte10** [eu-digital-green-certificates/dgca-verifier-app-android#69]
## Describe the bug

When you scan a random QR code that isn't related to the DGCA system at all (for example, a QR code that just contains text or a random URL) the error message is confusing / wrong. 

## Expected behaviour

Scanning a random QR code displays the error message "Invalid - Certificate is expired" - which is obviously wrong. There never was a valid certificate. "Certificate is expired" should only be shown for a syntactically correct, well-signed, expired cert. Not for random data. 

## Steps to reproduce the issue

1. Go on Google and search for "QR code"
2. Pick a random result and try to scan that with the verifier app
3. Notice that it says "Certificate is expired", not something like "this is not a valid QR code"

## Technical details

- Host Machine OS (Windows/Linux/Mac): Running the Android App 1.0.2 on Android 10

**Comment by oleksandrsarapulovgl** [comment]
@Leseratte10 could you please clarify what is expected behavior here?

What should we show exactly in the case?

FYI @Hendrik-Schmidt-Schierhorn-TSI

**Comment by oleksandrsarapulovgl** [comment]
Thank you @RalicaY ! Just to clarify - is it work on iOS? Because so far not sure we can differentiate between cryptographic error and this is not valid QR error. How would we no that? I think we wouldn't just be able to decode it

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl :  The problem with the message "Certificate is expired" is that it is a very specific cryptographic error and not just a general cryptographic error such as simply "Cryptographic Error" when reading the code.  Moreover, the message "Certificate expired" implies that the Code was cryptographically read and the certificate was evaluated as chronologically expired  which is misleading.

iOS Verifier Behaviour:  it does not scan the code at all and no output is displayed.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/78

**Comment by RalicaY** [comment]
Retest with 1.1.0 successful.
