### ISSUE TITLE
Missing UTC-Hint in "Date of TestResult" and "Date of Date of Collection"

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-verifier-app-android#72]
## Describe the bug
In the WalletApp it is not clear which timezone  is shown

## Expected behaviour
In the Test-QR-code should be clearly shown that it is the UTC-timezone as it is in the ios-version.

## Steps to reproduce the issue
1. create Testcertificate with location time-zone (for example 8:00 AM german time) as seen on screenshot:
![image](https://user-images.githubusercontent.com/81565021/120454129-e389cd80-c393-11eb-8921-3efdb603ed88.png)

2. Open VerifierApp
3. Scan the created test-certificate with location time-zone (for example 8:00 AM german time)
4. see test certificate
![image](https://user-images.githubusercontent.com/81565021/120455244-e1743e80-c394-11eb-87b3-faaf4ad6f302.png)
5. you find a different timezone without a hint

## Technical details
![image](https://user-images.githubusercontent.com/81565021/120454566-49765500-c394-11eb-81c5-cde251322b4d.png)

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix
add the hint (UTC) the Date of collection and Date of Test Result

**Comment by oleksandrsarapulovgl** [comment]
@rebwalz could you please clarify - what to display then if we receive zoned date time field? Should we add (UTC) to not zoned date time, and show zoned date time as is?

FYI @RalicaY

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/79

**Comment by rebwalz** [comment]
@oleksandrsarapulovgl i would do it same way as it is in the ios app. There is written (UTC) behind the time

**Comment by kerstin-oppermann-tsi** [comment]
Issue is fixed in Release 1.0.5 
![image](https://user-images.githubusercontent.com/81565834/122363540-50d35c00-cf59-11eb-9ab8-c30d497cc8ec.png)
