### ISSUE TITLE
Wrong Label "Country of Vaccination"

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-verifier-app-android#73]
## Describe the bug
In the VerifierApp it is shown the Label "Country of Vaccination"

## Expected behaviour
In the Test-QR-code should be written"Country of Test".

## Steps to reproduce the issue
1. Open VerifierApp
2. Scan a test-certificate
3. see test certificate
![image](https://user-images.githubusercontent.com/81565021/120456398-d968ce80-c395-11eb-8c0a-985fd91525db.png)
4. you see "Contry of Vaccination" instead of "Country of Test"

## Technical details
![image](https://user-images.githubusercontent.com/81565021/120454566-49765500-c394-11eb-81c5-cde251322b4d.png)

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix
Change Label to "Country of Test"

**Comment by RalicaY** [comment]
Issue is obsolete, because it doubles https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/68
