### ISSUE TITLE
Just beep and nothing displayed when scanning real Czech DGCA QR codes

### ISSUE THREAD

**Issue by brozkeff** [eu-digital-green-certificates/dgca-verifier-app-android#81]
## Describe the bug
Scanning real QR code from valid certificates issued by Czech Republic just beeps and does not display anything useful

## Expected behaviour

Green checkmark and/or some details that the certificate is OK or is not OK should be displayed.

## Steps to reproduce the issue

Get any valid certificate either from antigen, PCR test or vaccination from ocko.uzis.cz in PDF format and scan the QR code.

## Technical details

- Host Machine OS (Windows/Linux/Mac): Android 10 / MIUI

## Additional context

Xiaomi RedMi Note 8T, Android 10, dark mode activated, version 1.0.3-acc

**Comment by oleksandrsarapulovgl** [comment]
hi @brozkeff ! Could you please share specific QR?

**Comment by bogorad** [comment]
Same with a Catalan code after 1st dose. It _probably_ should be a tiny little bit more talkative :)

**Comment by kerstin-oppermann-tsi** [comment]
@brozkeff @bogorad can you please check if the problem longer exits with the latest app version? If yes and the codes are real productives one please refer an issue to this in https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues

**Comment by bogorad** [comment]
> if the problem longer exits with the latest app version

ver 1.1.1

Selected 'Spain'.

'Verification failed' and the app is preventing me from taking a screenshot (WTF?!).

Didn't get the 'refer to' part - isn't this an issue already?

**Comment by kerstin-oppermann-tsi** [comment]
@bogorad The screenshot issue is a security issue and is required :( Can you take a picture otherwise af the QR Code and the app screen?

**Comment by bogorad** [comment]
Too much hassle, sorry.

**Comment by kerstin-oppermann-tsi** [comment]
@bogorad  can you do a test with the app version 1.0.7. 
In the app versions 1.1.x business rules must be provided by the countries and that aren't yet.

**Comment by kerstin-oppermann-tsi** [comment]
The ticket is closed. See comment in the according ticket https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues/63

Production codes cannot be verified in the context of this repo. Only acceptance environment codes. Our apps only run to acceptance environment and not against productive.

**Comment by bogorad** [comment]
Tried the latest version. Still not working. Bravo!
