### ISSUE TITLE
Validation must consider valid valuesets

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-verifier-app-android#82]
The Verification App does not consider valid ValueSets, and will accept any data as Valid.
For Example: create a QR Code with any random data in the "Test Type" for the TEST QR Code.

You will notice that a Valid QR Code is returned, even though the data is not valid.

**Comment by LolloGithub** [comment]
Hi

from our tests, the verification app does not apply valueset validation.
I am not an expert and I do not know if this behaviour has been on purpose.

But it definitely serve a purpose for now. 
Until the DGCG gateway next version 1.1 will make update valueset globally available, we would have some issues in validate QR codes with updated valueset values.

**Comment by SchulzeStTSI** [comment]
The valueset validation is covered by the business rules execution and will be implemented together with the valueset sharing.

**Comment by psavva** [comment]
Ok, will follow via the business rules validation
