### ISSUE TITLE
When not set family and given name in issuance web, app shows NULL NULL in the top

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#85]
**Environment**
Issuance Web Portal https://issuance-dgca-test.cfapps.eu10.hana.ondemand.com/
Android Phone
Verifier App 1.0.3.-tst https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/releases/tag/1.0.3

**## Steps to reproduce the issue**

1. Click on Record Vaccination Certification
2. Fill out all mandatory fields
3. **Dont** fill out family and given name
![image](https://user-images.githubusercontent.com/81565834/121171624-023a0980-c857-11eb-98ed-da42a4c3b435.png)

4. Klick on NEXT
5. Scan certificate by Verifier App (app-tst-release-signed-1.0.3.apk)

**Actual result:**
App display NULL NULL in the top left corner
![image](https://user-images.githubusercontent.com/81565834/121172187-b76cc180-c857-11eb-85b2-0e3500c59056.png)

**Expected result:**
App should display nothing or standardised names

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment]
Logic: If one of the strings for GivenName, FamilyName, StandardisedGivenName, StandardisedFamilyName is null, it should become an empty string (containing "").
If GivenName && FamilyName are empty, use Standardised Names instead.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/92

**Comment by oleksandrsarapulovgl** [comment]
![Screenshot_1623306073](https://user-images.githubusercontent.com/82441124/121474786-3fc0a300-c9cd-11eb-89b2-20dda9666c15.png)

**Comment by kerstin-oppermann-tsi** [comment]
@oleksandrsarapulovgl  did you fixed this issue in release 1.0.4 ? If yes, it doesn't work correctly for this fact:
![image](https://user-images.githubusercontent.com/81565834/122229325-ecf95680-ceb8-11eb-83dd-ab27f5560535.png)
I only set STANDARDIZED FAMILY NAME, the rest is empty

![image](https://user-images.githubusercontent.com/81565834/122229568-292cb700-ceb9-11eb-90c0-27f796fadb91.png)

**Comment by oleksandrsarapulovgl** [comment]
![Screenshot_1623850742](https://user-images.githubusercontent.com/82441124/122229612-92b0c380-cec1-11eb-8f9a-a226b6f91070.png)
![Screenshot_1623850780](https://user-images.githubusercontent.com/82441124/122229617-93e1f080-cec1-11eb-9f29-458d79e86de5.png)

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/101

FYI @Hendrik-Schmidt-Schierhorn-TSI

**Comment by kerstin-oppermann-tsi** [comment]
Issue is fixed in Release 1.0.5
