### ISSUE TITLE
"Verification failed" when scanning authentic DGC QR code from the United Kingdom

### ISSUE THREAD

**Issue by cegg1** [eu-digital-green-certificates/dgca-verifier-app-android#88]
## Describe the bug

Scanning a real QR code from a valid DGC certificate issued by the United Kingdom results in "verification failed". 
The name of the holder is not shown on the screen.

## Expected behaviour

A green checkmark and details of the certificate should be displayed. Verification is expected to succeed when scanning a QR from an authentic, production DGC certificate. 

## Steps to reproduce the issue

- Download a valid DGC certificate from the [NHS App](https://www.nhs.uk/nhs-services/online-services/nhs-app/). (Notice there are several NHS apps, the correct one is com.nhs.online.nhsonline)
- A QR code containing an "HC1:" DGC is included in the certificate and can be read successfully using the [Swiss wallet app](https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.wallet).
- Open the app and ensure the latest certificates have been downloaded. 
- Scan the QR code and obtain a "verification failed" message. 

## Technical details

Host Machine OS: Android 10;     Dgca-verifier-app-android release v1.0.3

## Possible Fix

Add public keys of the United Kingdom's "NHS Digital" as a trusted authority.  

I can share production QR codes for testing through a private channel. 

![github](https://user-images.githubusercontent.com/28192843/121405259-bb323e00-c954-11eb-967f-267861abc806.jpg)

**Comment by ReneRumetshofer** [comment]
The same problem arises with genuine Lower Austrian certificates, version 1.0.4

**Comment by maluueu** [comment]
Same for genuine DE certificates

**Comment by kerstin-oppermann-tsi** [comment]
@cegg1 please can you check if the problem longer exits? We fixed some issues with the holders name (if provided).

If the issues with invalid certs further exits for real productive certs you should open an issue in https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues, if this is not, please provide any invalid code as example here or per email.

**Comment by martinbrook** [comment]
https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues/64

**Comment by kerstin-oppermann-tsi** [comment]
The ticket will be closed for two reasons:
1. see last comment in https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues/64
2. UK is not onboarded in the EU project and so it did not deliver dcc's for the gateway
