### ISSUE TITLE
Scanning genuine DGC QR code from Spain results in "verification failed"

### ISSUE THREAD

**Issue by cegg1** [eu-digital-green-certificates/dgca-verifier-app-android#94]
## Describe the bug

Scanning a QR code from a real, valid DGC certificate issued by Spain results in "verification failed".
The name of the holder is nevertheless shown on the screen. 

## Expected behaviour

A green checkmark and details of the certificate should be displayed. Verification is expected to succeed when scanning a QR from an authentic, production DGC certificate.

## Steps to reproduce the issue

- Download a valid DGC certificate from [Spain's official web portal](https://cvd-cc.sanidad.gob.es/).
- A QR code containing an "HC1:" DGC is included in the certificate and can be read successfully using the [Swiss wallet app](https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.wallet).
- Open the app and ensure the latest certificates have been downloaded. 
- Scan the QR code and obtain a "verification failed" message.

## Technical details

- Host Machine OS: Android 10; Dgca-verifier-app-android release v1.0.3

## Possible Fix

Add public keys of Spain's "Ministerio de Sanidad"  as a trusted authority.
I can share privately production QR codes, for testing.

![github2](https://user-images.githubusercontent.com/28192843/121671221-30f9ef00-caa6-11eb-9bca-8dfe2f7f5f41.jpg)

**Comment by mapelo** [comment]
The certificate from the Spanish Ministry of Health is different from each of the certificates issued by the regions in Spain. So, add public keys of Spain's "Consejerías de Sanidad" authority as trusted.

**Comment by chrloch** [comment]
The app does not have a builtin list of trusted certificates. If the signer certificate is not on the environment's gateway, the behavior is correct.
